[package]
name = "tokio-hrtime"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
libc = "0.2"
pin-project-lite = "0.2"
tokio = { version = "1", default-features = false, features = ["net"] }

[features]
test = ["tokio/rt", "tokio/macros"]
